"""Generate the "famous beats" call files from their text grids.

Reads calls/call_spec_famous.txt, parses every pattern in it (call_06, call_07,
call_08) and writes calls/call_NN.mid in the same format as the human-made
calls: type 0, one track, 480 ticks per beat, 120 BPM, 4/4, velocity 110, each
hit one sixteenth long, end of track at exactly two bars.

The grids are parsed from the spec file, not retyped here, so the spec stays the
single source. MIDI notes come from config/voices.json.

Real vs. chosen: these calls are CHOSEN by us. They are our own transcriptions
of well-known drum patterns on a 120 BPM sixteenth grid, not copies of any
recording or MIDI file. Unlike call_01..05 they are generated by this script
rather than exported from Ableton.

Usage (from the repo root):  python -m src.make_calls
"""

import json
import pathlib
import re

import mido

from src import constants as c

ROOT = pathlib.Path(__file__).resolve().parent.parent
CALLS = ROOT / "calls"
SPEC = CALLS / "call_spec_famous.txt"

TICKS_PER_BEAT = 480
VELOCITY = 110
TICKS_PER_STEP = TICKS_PER_BEAT * c.BEATS_PER_BAR // c.STEPS_PER_BAR
CALL_TICKS = c.CALL_STEPS * TICKS_PER_STEP

HEADER_RE = re.compile(r"^(call_\d+) - ")
# "Bar 1   Kick        x... x... .... ...."  or  "        Snare       .... ...."
ROW_RE = re.compile(r"^(?:Bar (\d+))?\s+(\S.*?)\s+((?:[x.]{4} +){3}[x.]{4})\s*$")


def load_voices():
    return json.loads((ROOT / "config" / "voices.json").read_text())["voices"]


def parse_spec(text, voice_names):
    """Return {call name: {voice name: [bool] * CALL_STEPS}} in spec order."""
    patterns, name, bar = {}, None, None
    for line in text.splitlines():
        header = HEADER_RE.match(line)
        if header:
            name, bar = header.group(1), None
            patterns[name] = {}
            continue
        row = ROW_RE.match(line)
        if not row or name is None:
            continue
        bar_label, voice, cells = row.groups()
        if bar_label:
            bar = int(bar_label)
        if voice not in voice_names:
            raise ValueError(f"{name}: unknown voice {voice!r}")
        if bar is None or not 1 <= bar <= c.CALL_BARS:
            raise ValueError(f"{name}: row for {voice!r} has no valid bar")
        steps = patterns[name].setdefault(voice, [None] * c.CALL_STEPS)
        start = (bar - 1) * c.STEPS_PER_BAR
        if steps[start] is not None:
            raise ValueError(f"{name}: {voice!r} given twice in bar {bar}")
        steps[start : start + c.STEPS_PER_BAR] = [ch == "x" for ch in cells.replace(" ", "")]
    for name, grid in patterns.items():
        for voice, steps in grid.items():
            if None in steps:
                raise ValueError(f"{name}: {voice!r} is missing a bar")
    return patterns


def grid_events(grid, voices):
    """Absolute-tick events, note_offs before note_ons on the same tick."""
    events = []
    for v in voices:
        for step, hit in enumerate(grid.get(v["name"], [])):
            if hit:
                tick = step * TICKS_PER_STEP
                events.append((tick, 1, v["idx"], "note_on", v["midi_note"]))
                events.append((tick + TICKS_PER_STEP, 0, v["idx"], "note_off", v["midi_note"]))
    return sorted(events)


def build_midi(grid, voices):
    track = mido.MidiTrack()
    track.append(mido.MetaMessage("set_tempo", tempo=mido.bpm2tempo(c.BPM), time=0))
    track.append(
        mido.MetaMessage("time_signature", numerator=c.BEATS_PER_BAR, denominator=4, time=0)
    )
    now = 0
    for tick, _, _, kind, note in grid_events(grid, voices):
        velocity = VELOCITY if kind == "note_on" else 0
        track.append(mido.Message(kind, note=note, velocity=velocity, time=tick - now))
        now = tick
    track.append(mido.MetaMessage("end_of_track", time=CALL_TICKS - now))
    mid = mido.MidiFile(type=0, ticks_per_beat=TICKS_PER_BEAT)
    mid.tracks.append(track)
    return mid


def main():
    voices = load_voices()
    patterns = parse_spec(SPEC.read_text(), {v["name"] for v in voices})
    if not patterns:
        raise SystemExit(f"no patterns found in {SPEC}")
    for name, grid in patterns.items():
        path = CALLS / f"{name}.mid"
        build_midi(grid, voices).save(path)
        counts = ", ".join(f"{voice} {sum(steps)}" for voice, steps in grid.items())
        print(f"wrote {path.relative_to(ROOT)}  ({counts})")


if __name__ == "__main__":
    main()
